name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go: [1.16, 1.18]

    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Install Dependencies
      run: |
        go version
        go get golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test With Coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Run Vet & Lint
      run: |
        go vet ./...
        golint -set_exit_status ./...
