name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Install Dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test With Coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Run Vet & Lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go vet ./...
        golint -set_exit_status=1 ./...
